### ISSUE TITLE
Un-Select Annotation

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#12]
Can you create an unselectAnnotation event, so we can change control state of the previously selected annotation. i.e. unhighlight an annotation that was previously highlighted through the selectAnnotation event.

**Comment by rsimon** [comment]
This is basically available now, since one of the latest releases ([v2.2.0](https://github.com/recogito/annotorious-openseadragon/releases/tag/v2.2.0)). Available events are as follows:

- `selectAnnotation` the user selected an existing annotation
- `createSelection` the user created a new selection shape
- `createAnnotation` or `updateAnnotation` the user hit 'Ok' on the editor popup, de-selecting the annotation
- `cancelSelected` the user hit 'Cancel' on the editor popup (or clicked outside, or into another annotation, also cancelling editing)

For `cancelSelected` you can distinguish whether the cancel has happened on an existing annotation or a newly created shape by inspecting the annotation object handed to the handler function: it's either of `type: 'Annotation'` or `type: 'Selection'`.
