### ISSUE TITLE
Retrieve annotations which intersect with their bounding box

### ISSUE THREAD

**Issue by hsellik** [recogito/annotorious-openseadragon#134]
Since you keep the spatial index for bounding boxes, would it be possible to expose a method to return other annotations whose bounding boxes are intersecting with the annotation specified?

> **.getAnnotationsIntersecting**

> `getAnnotationsIntersecting(arg);`

> Returns the annotations whose bounding boxes intersect with the bounding box of the specified annotation.

> Argmument arg is of type `String` or `Object` with the value of the annotation or the annotation ID respectively.

It's not a perfect intersection match for the annotations, but at least the bounding boxes match and it's close enough for me.

It's not working for sure, but I was thinking roughly something like this: https://github.com/recogito/annotorious-openseadragon/compare/main...hsellik:annotorious-openseadragon:bounding-box

What do you think?

**Comment by rsimon** [comment]
Hi,

I like the idea - could be a really useful feature! As you say a fully complete implementation would have to check intersections between actual shapes (I guess by providing separate tests box/box, box/poly, poly/poly, and for point and line shapes). But this might be a nice first step. Would you mind sending a PR? I think I might tweak the plumbing a bit, but otherwise I'm happy to include this.

Two caveats:
- This will only work for the OpenSeadragon version, because Annotorious standard doesn't use a spatial index.
- I'm currently on vacation. Merging and release might take a bit :-)

**Comment by hsellik** [comment]
Hi!

Made the pull request https://github.com/recogito/annotorious-openseadragon/pull/139. 

Tried to make it work locally first, but couldn't. So as you said, it needs some tweaks, still.

**Comment by rsimon** [comment]
Got it - many thanks! There were only two small issues:
- `getBounds` wasn't a method of the AnnotationStore. It was just a utility function for local use, not visible outside the `AnnotationStore.js` source file
- In case the user handed an annotation ID into `getAnnotationsIntersecting` the ID wasn't actually resolved to an annotation.

I made a handful of small tweaks to fix this. The feature should be good to go now. Thanks again - a nice addition!
