### ISSUE TITLE
Could you please share the openseadragon-annotorious.js file?

### ISSUE THREAD

**Issue by ufuk23** [recogito/annotorious-openseadragon#25]
Could you please share the openseadragon-annotorious.js file? I found a minified js file called openseadragon-annotorious.min.js, but it is hard to understand even if I make the file unminified.

**Comment by rsimon** [comment]
There is no single unminfied file, because this project uses a bundler. You can find the original source code in the [src folder of this repo](https://github.com/recogito/annotorious-openseadragon/tree/master/src), and instructions on how to build from source here:

https://recogito.github.io/guides/development-setup/

The steps are simple - just run the following two commands in the project folder:

```shell
$ npm install
$ npm run build
``` 

The first step downloads the external project dependencies, the second builds the distribution bundle. You'll need recent versions of Node.js and npm installed on your system. Hope this helps!

**Comment by ufuk23** [comment]
Thanks for your reply. I did everything you said, but I could not have the openseadragon-annotorious.js original file. The file I have is still obfuscated even though I delete the optimization code line from the webpack-config.js. Have you got any suggestions?

**Comment by rsimon** [comment]
What exactly are you trying to achieve with the unobfuscated file? If you want to make a change to the Annotorious code, why not just make the change in the source code, and rebuild?

As I said, since the project uses a bundler (like pretty much any other project out there), there __is__ no original unobfuscated file, and it's probably impossible to create what you are looking for. There's just the original source code & the `package.json` with the dependencies.
