### ISSUE TITLE
Touch navigation breaks after starting pinch/pan gesture on annotation

### ISSUE THREAD

**Issue by rsimon** [recogito/annotorious-openseadragon#44]
It looks like touch navigation breaks when __starting__ a touch gesture on an annotation. Once this was done once, touch navigation remains broken! As long as you just select an annotation (with a single tap), or do pan/pinch gestures outside of annotation shapes, things work just fine.

Note: this is almost certainly related to OSD's weird ways of handling touch/mouse events, and might (hopefully) go away with the release of OSD 3.0, for which event handling was thoroughly revised.

**Comment by Hero-Solutions** [comment]
I'm not sure if this has to do with the way OSD handles touch input, but even if it does, I built their latest revision from source and the Annotorious plugin still seems to behave the exact same way when selecting an annotation from a touch device. That is, if their new touch handling is already available in their source code on Github.

I fiddled around a bit with the code and found that the line below seems to be the one causing the bug. When commented out, the bug stops occurring, but then of course new shapes pop up every time an annotation is selected.

https://github.com/recogito/annotorious-openseadragon/blob/2c16cbf72cb9644903ef76993ef3bf309b48b726/src/OSDAnnotationLayer.js#L372

I'm quite puzzled as to how this could be causing the bug, since removing the shape seems completely unrelated to any kind of input handling.

It does look like we can avoid the bug when removing the existing shape in a different way, for example through the ```setTimeout``` function:
```
      setTimeout(function() { shape.parentNode.removeChild(shape); }, 0);
```
I've currently implemented it this way as a really hackish workaround in my project (a fork of this repo), but it would still be nice to see this particular bug fixed. It's very important for my use case that the Annotorious plugin for OSD works properly on a touch device.

**Comment by rsimon** [comment]
@Hero-Solutions I haven't tried out the new OSD version yet. Hoping to do so on the weekend. But, hey - many thanks for testing this out & debugging already. This info is really helpful!

Hm, I was under the assumption that the old OSD `MouseTracker` is no longer available in the new version. But I definitely need to read my way through the new docs first. 

Anyways: the `shape` that gets removed  in that line does have a `MouseTracker` attached, so there might be some connection to that. (Destroying the shape without destroying the `MouseTracker` first perhaps.) It's weird that setTimeout changes the bevavior though. Thanks for figuring this out! Definitely sounds like an important piece to the puzzle. I'll investigate...

**Comment by rsimon** [comment]
For the record: I moved the line `shape.parentNode.removeChild(shape);` to the bottom, after the rest of the tool initialization is complete. (Which essentially has the same effect as deferring with `.setTimeout`, just without using `.setTimeout`.)

I have __still__ no idea why this is happening, but suspect that there must be some kind of interal OpenSeadragon mechanism that interferes. If anyone has ideas on this one day, do let me know. For now, I'm satisfied enough that this is working ;-)

**Comment by Hero-Solutions** [comment]
Thank you for looking into this once again. However, I'm afraid the touch navigation is still broken with the latest commit - the asynchronous removal of the shape is still the only way I can personally find to work around the bug, so I have kept my current implementation of the workaround.

**Comment by rsimon** [comment]
Wait - weird. You are right. I think I might have been too hectic this morning. Made the change and maybe tested it before the dev server had recompiled... I reverted back to the `.setTimeout` workaround.
