### ISSUE TITLE
Delete Annotation

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#5]
I'm getting an error message when I delete an annotation.

```
openseadragon-annotorious.min.js:1 Uncaught ReferenceError: annotation is not defined
    at Object.onAnnotationDeleted (openseadragon-annotorious.min.js:1)
    at Object.u [as click] (openseadragon-annotorious.min.js:1)
    at HTMLButtonElement.b (openseadragon-annotorious.min.js:1)
```

**Comment by rsimon** [comment]
Looks like a bug. Thx for reporting, will look into it!

**Comment by ZENUAV** [comment]
This happens through the UI. Select annotation, use drop-down option 'Delete'. I have not tried deleting an annotation through code yet.

**Comment by ZENUAV** [comment]
Can I test these changes? Had the min.js file been updated?

**Comment by rsimon** [comment]
I didn’t update the demo distribution min.js yet (but will definitely do so, sometime over the next days). Right now the fix is only in the source code, you‘d need to [run or build off the master branch](https://github.com/recogito/annotorious-openseadragon/wiki/Contributing). But as I said, I‘ll update the demo with latest state within days.

**Comment by rsimon** [comment]
Just a quick heads-up: I updated the build on the demo site. The fix should now be available.

**Comment by ZENUAV** [comment]
Fab! Thanks, I’ll try it out soon.


On 13 May 2020, at 14:43, Rainer Simon <notifications@github.com> wrote:

﻿

Just a quick heads-up: I updated the build on the demo site. The fix should now be available.
