### ISSUE TITLE
When sequenceMode is enabled on SeaDragon, Annotorious annotations aren't specific to an image.

### ISSUE THREAD

**Issue by Garet-Jax** [recogito/annotorious-openseadragon#52]
Seadragon supports displaying multiple images using "sequenceMode".  When this is enabled Seadragon allows one instance of the viewer to display multiple images.  Annotorious seems to place the annotation on the canvas without regard to the intended image.  As the image changes in Seadragon, the original annotation stays.

**Comment by rsimon** [comment]
Yes, that's right. Annotorious doesn't support sequence mode yet.

**Comment by rsimon** [comment]
That would be great, thanks!

I wonder which aspects Annotorious should cover. In principle, loading annotations is up to the host app, anyway, so perhaps not that many? Probably, Annotorious should:

- clear the annotations when OSD switches to a new image

- update the dimensions of the annotation layer (and the ID stored for the image, which gets inserted in the annotation target)

But that might be all that's needed?

**Comment by rsimon** [comment]
@umesh-timalsina after re-reading your code (and finally understanding how sequence mode works :-) I realized this can be solved entirely from the outside. I'll try to refactor your code into a separate plugin. That would keep everything nicely together (both the functionality you added to the core + the additional code that's now in the HTML page).

**Comment by umesh-timalsina** [comment]
@rsimon Okay. I have worked on a [plugin](https://github.com/symbench/scm/blob/9ab38f06896d19a8a6b36f1e431e3f40d50432c5/js/circuit-annotator/src/Components/OpenSeadragon/OSDAnnotatorPaginationPlugin.js) that does exactly what you suggested here, assuming that the annotation layer is cleared with the changes made in #60. But I guess the clearing of annotations can also be handled using OSDEvents.

**Comment by rsimon** [comment]
Hi @umesh-timalsina exactly - I simply took your original plugin code that was inside the `sequence-mode.html` file, and added the API calls to cancel the selection and clear the annotation layer on page change. Luckily, the resizing of the annotation layer happens automatically, because OpenSeadragon also fires the `load` event on page change.

I created a self-contained plugin project here:
https://github.com/recogito/recogito-client-plugins/blob/main/packages/annotorious-sequence-mode/src/index.js

Unfortunately, because I moved the code over manually, that now also means your Git attribution is wiped. Everything is marked with my name. Sorry - it's definitely not my intention to erase the attribution. I gave credit in the README, I hope that's ok:
https://github.com/recogito/recogito-client-plugins/tree/main/packages/annotorious-sequence-mode

**Comment by umesh-timalsina** [comment]
@rsimon No worries. There are some enhancements that I think we can add to the plugin. I have already have them working can can contribute it as a PR to that plugin. Please let me know what you think of the following:
1. Monkey patching the `annotatator` to add a function called `getAllAnnotations` when is sequence mode that will simply provide annotations for all images loaded in the viewer.
2. Optional Initial Annotations based on URL: An initial set of annotations to be loaded into the viewer once we have the viewer open in sequence mode. 
3. Optional Emitter Events: Passing in a `tiny-emitter` instance to optionally emit events for programatically added annotations. This has been once of our requirements as we do template matching. Once the templates are matched, the added annotations (programitically) trigger further queries to the server. This  might not be a requirement for every one though.

**Comment by DiegoPino** [comment]
@rsimon @umesh-timalsina sorry for jumping into this conversation in here. Trying to catch up with this issue since we are already doing sequence mode (single image at the same time) without any direct changes on Annotorius and wonder/what is that can not be done directly right now?

An example here:

https://play.archipelago.nyc/do/6f1da83c-2bf3-4cc3-bf56-d51bd3a97948

We just wrapped a bit of normal JS (+jquery) and Open Seadragon Events. But we also built an REST API around putting/reading/deleting Annotations since all our Annotations are saved at the Main Digital object level in JSON with the Source Image as target to fetching what we need  is quite easy.

My JS is way too (really) rudimentary to be of any use  for you both but that said it works fine. (https://github.com/esmero/format_strawberryfield/blob/1.0.0-RC3/js/iiif-openseadragon_strawberry.js)


each annotation ends with this format (for easy identification to which tile/image it belongs)

```JSON
[
 "https:\/\/play.archipelago.nyc\/cantaloupe\/iiif\/2\/6e3%2Fimage-dscf6509-jpg-5548a45d-bef9-48b6-9803-f986a0e07731.tiff\/info.json": [
            {
                "id": "#05aacd4a-706b-47ea-b879-e50ec0348513",
                "body": [
                    {
                        "type": "TextualBody",
                        "value": "Puppy face!",
                        "created": "2021-06-23T16:16:13.711Z",
                        "creator": {
                            "id": "\/user\/1",
                            "name": "admin"
                        },
                        "purpose": "commenting"
                    },
                    {
                        "type": "TextualBody",
                        "value": "Dog",
                        "created": "2021-06-23T16:16:13.712Z",
                        "creator": {
                            "id": "\/user\/1",
                            "name": "admin"
                        },
                        "purpose": "tagging"
                    }
                ],
                "type": "Annotation",
                "target": {
                    "source": "https:\/\/play.archipelago.nyc\/cantaloupe\/iiif\/2\/6e3%2Fimage-dscf6509-jpg-5548a45d-bef9-48b6-9803-f986a0e07731.tiff",
                    "selector": {
                        "type": "SvgSelector",
                        "value": "<\/polygon><\/svg>"
                    }
                },
                "@context": "http:\/\/www.w3.org\/ns\/anno.jsonld"
            }
        ]
```
Am I missing some use case? Would love to understand more 

Again sorry, I may be out-of-topic

**Comment by umesh-timalsina** [comment]
@DiegoPino You are exactly right. Initially, there was some discussion around supporting sequence mode because the annotations were not cleared on viewer page change (More context in #32, specifically [this](https://github.com/recogito/annotorious-openseadragon/issues/32#issuecomment-861016463) and [this](https://github.com/recogito/annotorious-openseadragon/issues/32#issuecomment-861194784)) and it was decided that we need to clear all the annotations on viewer page change added in #60. Upon further investigation @rsimon realized pointed that this can be handled entirely outside of the core, however to cover most general use cases, a [simple pagination plugin](https://github.com/recogito/recogito-client-plugins/blob/main/packages/annotorious-sequence-mode/src/index.js) could be maintained. The plugin will:
1. Maintain a list of annotations for a page when OSD viewer is in sequence mode.
2. Clear annotations on viewer page change and load any previous annotations kept by the [plugin](https://github.com/recogito/recogito-client-plugins/blob/main/packages/annotorious-sequence-mode/src/index.js).

**Comment by rsimon** [comment]
@umesh-timalsina +1 on features 1 & 2, those sound really good! I think I don't quite understand the third one. Do you mean annotations get added via JS, and you need to react to that? Wouldn't it be easier to handle directly in the code that adds the annotations?

> I still see that the annotation layer is cleared on pageChange is it your intention to remove that code from the repo as well?

Ah - you are right of course! I forgot to remove that. (Just too much activity recently :-D)

**Comment by rsimon** [comment]
@DiegoPino exactly - just to second everything @umesh-timalsina said: the sequence mode plugin doesn't really add anything to Annotorious you couldn't build yourself. But it simplifies sequence mode by handling the common stuff.

**Comment by DiegoPino** [comment]
Thanks so much to both @rsimon and @umesh-timalsina. I totally understand. This is very useful. Sorry for the confusion

**Comment by rsimon** [comment]
Since the the [sequence mode plugin](https://github.com/recogito/recogito-client-plugins/tree/main/packages/annotorious-sequence-mode) is now official, I think we can close the issue! 🎉
