### ISSUE TITLE
Handles not aligned with selected area in Safari

### ISSUE THREAD

**Issue by johnguirgis** [recogito/annotorious-openseadragon#62]
When creating or selecting (when not in ```readOnly``` mode) an annotation in Safari (version 14.1.1), the handles are not aligned with the annotated region.
<img width="641" alt="Screen Shot 2021-06-21 at 3 50 07 PM" src="https://user-images.githubusercontent.com/62853290/122819357-5d80e880-d2a8-11eb-829d-8b1d7c9ee3bc.png">

**Comment by rsimon** [comment]
Just to confirm: does the offset between shape and handle shift when you zoom? (Offset should reach zero add you approach the highest zoom level.)

**Comment by johnguirgis** [comment]
The offset does change when zooming but even at the max zoom level it is still there 

https://user-images.githubusercontent.com/62853290/122820874-1d226a00-d2aa-11eb-979c-429368db2ae3.mp4

**Comment by rsimon** [comment]
Ok, got some additional reports from friends testing this on Mac + did some digging. It's confirmed that this is because an unsupported feature in Safari. For the record:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform-origin

Two possible solutions to this are:
1. Go via CSS entirely (currently the transform is done via an SVG attribute - which is what Safari doesn't like)
2. Scale the handle radius rather than do a transform (might be a simpler solution)
