### ISSUE TITLE
Problems with sorting shapes

### ISSUE THREAD

**Issue by erikradisch** [recogito/annotorious-openseadragon#68]
Shapes are not always sorted as expected. 
See, for example http://kuchatest.saw-leipzig.de/depiction/136 (I send the pw per pm). I implemented a show on hover behavior. However, several shapes with less area are sorted before a huge one and therefore not shown.

**Comment by rsimon** [comment]
Hi @erikradisch,

first off: the effect looks great! I think I need to add that incorprate to the main codebase, too, somehow :-) 

Hm, yes, the shapes are supposed to be sorted by area, so that the smallest one is always on top. I noticed that the annotations in your case are not `<polygon>`s, however. But `<path>`s. I assume they were created by your multi-polygon extension?

The recent Annotorious releases only contained area computation for `<rect>`s and `<polygons>`. I think they would have raised an exception for `<path>` shapes. Did you make any changes to the [EmbeddedSVG](https://github.com/recogito/annotorious/blob/main/src/selectors/EmbeddedSVG.js) class to avoid this? If so, what does your area computation code look like?

The latest release did add area computation code for paths. I think it *might* have problems dealing with multi-polygon shapes, but should handle single (closed or open) paths. If you're not using the latest release yet, upgrading might also help.

**Comment by erikradisch** [comment]
Sure! I forgot to adjust the algorithm for calculating the areas!!! thanks for that tip! That did already the trick!!
